spring:
  profiles: default

# Configurações do banco de dados H2 com JDBC
spring.datasource:
  h2:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

# Configurações do banco de dados MySQL com JPA
spring.datasource.mysql:
  url: jdbc:mysql://localhost:3306/example_db?useSSL=false&serverTimezone=UTC
  username: example_user
  password: example_password
  driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: update
  show-sql: true

h2:
  console:
    enabled: true
    path: /h2-console